# Generated by Django 5.1.7 on 2025-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('under_auction', 'Under Auction'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
    ]
